beat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sel/', include('sel.urls')),
]

sel/urls.py
from django.urls import path
from . import views

app_name = 'sel'
b=views.Games()

urlpatterns = [
    #path('', index, name='index'),
    path('cot/', b.cot, name='cot'),
    path('ans/', b.ans, name='ans'),
    path('look/', b.look, name='look'),
    path('signup/', b.signup, name='signup'),
    path('login/', b.login, name='login'),
    path('loc/', b.loc, name='loc'),
    path('all_logout', b.all_logout, name='all_logout'),
]

sel/models.py
from django.db import models

# Create your models here.

sel/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate, login
import random
import time
# Create your views here.

class Games:
    def __init__(shelf):
        shelf.H = 6
        shelf.W = 8

        shelf.name = ''
        shelf.count = 0
        shelf.turn = 0
        shelf.who = {}
        spell = 'abcdefghijklmnopqrstuvwx'
        shelf.board = spell*2

        shelf.params = {
        'title':shelf.name,
        'user':[],
        'board':shelf.board,
        'entry':0,
        'turn':{},
        'color':{},
        'acount':{},
        'point':{},
        'get':{},
        'all_get':{},
        'che':{},
        'before':{},
        'before_x':{},
        'before_y':{},
        'group':[],
        'group_num':0,
        'member_num':{},
        'next_player':[],
        'wait':0,
    }

    def all_check(shelf, user, mem):
        shelf.params['message'] = 'check_def'
        if len(shelf.params['all_get'][user]) != 0:
            shelf.params['message'] = 'check_if'
            for i in range(shelf.H):
                for j in range(shelf.W):
                    cot = 0
                    for mass in shelf.params['all_get'][user]:
                        if mass == shelf.params['acount'][user][i][j]:
                            shelf.params['che'][user][i][j] = mass
                            cot = 1
                            break

                    if cot == 0:
                        shelf.params['che'][user][i][j] = '*'

        else:
            shelf.params['message'] = 'check_else'
            for i in range(shelf.H):
                for j in range(shelf.W):
                    shelf.params['che'][user][i][j] = '*'

        try:
            for enemy in shelf.params['group'][mem]:
                shelf.params['che'][enemy] = shelf.params['che'][user].copy()

        except:
            a = 'None'


    def cot(shelf, req):
        user_check = str(req.user)

        if req.method == 'POST':

            if 'hit' in req.POST:
                hw = str(req.POST['hit']).split('/')
                height = int(hw[0])
                width = int(hw[1])

                shelf.params['before_y'][user_check].append(height)
                shelf.params['before_x'][user_check].append(width)

                shelf.params['message'] = 'hit'
                shelf.params['height'] = str(height)
                shelf.params['width'] = str(width)

                mass = shelf.params['acount'][user_check][height][width]
                shelf.params['word'] = mass

                if shelf.params['turn'][user_check] == 1:
                    shelf.params['turn'][user_check] = 2
                    shelf.params['before'][user_check] = mass
                    shelf.params['che'][user_check][height][width] = mass

                elif shelf.params['turn'][user_check] == 2:
                    shelf.params['che'][user_check][height][width] = mass
                    shelf.params['message'] = 'double'

                    if shelf.params['before'][user_check] == mass:
                        shelf.params['get'][user_check].append(mass)
                        shelf.params['all_get'][user_check].append(mass)
                        mem = shelf.params['member_num'][user_check]

                        try:
                            for enemy in shelf.params['group'][mem]:
                                shelf.params['all_get'][enemy] = shelf.params['all_get'][user_check].copy()
                                shelf.params['che'][enemy] = shelf.params['che'][user_check].copy()

                        except:
                            a = 'None'

                        shelf.params['turn'][user_check] = 100

                    else:
                        shelf.params['turn'][user_check] = 3


            elif 'load' in req.POST:
                shelf.params['message'] = 'load'
                if 3 <= shelf.params['turn'][user_check]:

                    shelf.params['message'] = 'loads'
                    shelf.params['before'][user_check] = '*'
                    shelf.params['turn'][user_check] = 0

                    mem = int(shelf.params['member_num'][user_check])
                    many = len(shelf.params['group'][mem])

                    shelf.all_check(user_check, mem)

                    shelf.params['before_y'][user_check] = []
                    shelf.params['before_x'][user_check] = []

                    shelf.params['message'] = 'loads2'

                    for i in range(many):
                        shelf.params['message'] = 'loads3'
                        if shelf.params['group'][mem][i] == user_check:
                            if i == many-1:
                                shelf.params['next_player'][mem] = shelf.params['group'][mem][0]

                            else:
                                shelf.params['next_player'][mem] = shelf.params['group'][mem][i+1]

                    next_player = shelf.params['next_player'][mem]
                    shelf.params['turn'][next_player] = 1

            else:
                shelf.params['message']='None'
                return redirect(to='/sel/ans')

        return redirect(to='/sel/ans')

    def ans(shelf, req):
        return render(req, 'sel/ans.html', shelf.params)

    def look(shelf, req):
        return render(req, 'sel/look.html', shelf.params)


    def all_logout(shelf, req):
        user_check = str(req.user)

        shelf.params['entry'] -= 1
        shelf.params['turn'].pop(user_check)
        shelf.params['user'].remove(user_check)
        shelf.params['get'].pop(user_check)
        shelf.params['all_get'].pop(user_check)
        shelf.params['before'].pop(user_check)
        shelf.params['before_y'].pop(user_check)
        shelf.params['before_x'].pop(user_check)

        try:
            shelf.params['enemy'].pop(user_check)
            return redirect(to='/sel/login')

        except:
            return redirect(to='/sel/login')


        try:
            mem = shelf.params['member_num'][user_check]
            shelf.params['group'][mem].pop(user_check)
            return redirect(to='/sel/login')

        except:
            return redirect(to='/sel/login')

        return redirect(to='/sel/login')


    def signup(shelf, req):
        #user_check = req.user
        shelf.params['username'] = 'sel'
        if req.method == 'POST':
            username = req.POST['username_data']
            password = req.POST['password_data']
            print('username=', username, 'password=', password)
            try:
                user = User.objects.create_user(username, '', password)
                shelf.params['username'] = 'just recomend'

            except IntegrityError:
                shelf.params['username'] = 'already'

        return render(req, 'sel/signup.html', shelf.params)

    def login(shelf, req):
        if req.method == 'POST':
            username_data = req.POST['username_data']
            password_data = req.POST['password_data']
            user = authenticate(req, username=username_data, password=password_data)

            if user is not None:
                if username_data in shelf.params['user']:
                    return redirect(to='/sel/login')

                else:
                    shelf.params['user'].append(username_data)
                    login(req, user)

                    shu = ''.join(random.sample(shelf.board, len(shelf.board)))

                    cell = [[] for i in range(shelf.H)]
                    k = 0
                    for i in range(shelf.H):
                        for j in range(shelf.W):
                            cell[i].append(shu[k])
                            k += 1


                    shelf.params['acount'][str(username_data)] = cell.copy()
                    shelf.params['get'][str(username_data)] = []
                    shelf.params['before'][str(username_data)] = '*'

                    shelf.params['before_x'][str(username_data)] = []
                    shelf.params['before_y'][str(username_data)] = []

                    shelf.params['all_get'][str(username_data)] = []

                    check = [['*'] * shelf.W for i in range(shelf.H)]
                    shelf.params['che'][str(username_data)] = check.copy()

                    shelf.params['entry']+=1

                    if shelf.params['wait'] == 2:
                        goal_time = time.time()

                        if goal_time - shelf.params['start_time'] < 60:
                            shelf.params['turn'][str(username_data)] = 0

                            entry_a = str(shelf.params['user'][shelf.params['entry']-3])
                            entry_b = str(shelf.params['user'][shelf.params['entry']-2])
                            entry_c = str(shelf.params['user'][shelf.params['entry']-1])


                            shelf.params['acount'][entry_c] = shelf.params['acount'][entry_b].copy()
                            shelf.params['che'][entry_c] = shelf.params['che'][entry_b].copy()
                            shelf.params['all_get'][entry_c] = shelf.params['all_get'][entry_b].copy()

                            shelf.params['wait'] += 1


                            shelf.params['member_num'][str(username_data)] = shelf.params['group_num']
                            shelf.params['group'][shelf.params['group_num']].append(str(username_data))
                            shelf.params['group_num'] += 1

                        else:
                            shelf.params['wait'] = 0
                            shelf.params['turn'][str(username_data)] = 1
                            shelf.params['wait'] += 1


                            shelf.params['group'].append([str(username_data)])
                            shelf.params['group_num'] += 1

sel/templates/sel/ans.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{title}}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">

    </head>
    <body>
        <br>
        <div style="text-align:center">
            <h1>account is ={{request.user.username}}</h1>
            <form action="{% url 'sel:cot' %}" method="post">
                {% csrf_token %}
                <input type="submit" name="load" value="load" class="btn btn-primary" style="margin:9px;height:100px;width:80px">
            </form>
            {% if acount %}
                {% for name, list in che.items %}
                {% if name == request.user.username %}
                    {% for line in list %}
                        <div style="display:inline-flex">
                            {% for column in line %}

                                {% if column == '*' %}
                                    <form action="{% url 'sel:cot' %}" method="post">
                                        {% csrf_token %}
                                        <font face='Century' size='6'><input type="submit" name="hit" value="{{ forloop.parentloop.counter0 }}/{{ forloop.counter0 }}"
                                            style="margin:9px; height:100px; width:100px; text-align:center;"></font>
                                    </form>

                                {% else %}

                                    <font face='Century' size='6'><input type="submit" name="hit" value="{{ column }}"
                                        style="margin:9px; height:100px; width:100px; background-color:black; color:white; text-align:center;"></font>

                                {% endif %}


                            {% endfor %}
                        </div>

                    <br>
                    {% endfor %}
                {% endif %}
                {% endfor %}
            {% endif %}


            <h2>entry={{entry}}</h2>

            <div style="display:inline-flex">
                {% if turn %}
                    <h2>turn = </h2>
                    {% for name, number in turn.items %}
                        <h2>{{name}} : {{number}}/</h2>
                    {% endfor %}
                {% endif %}
            </div>
            <br>

            <div style="display:inline-flex">
                {% if group %}
                    {% for name, num in member_num.items %}
                        {% if name == request.user.username %}
                            <!--{{name}}:{{num}}<br>-->

                                {% for list in group %}
                                    {% if num == forloop.counter0 %}
                                        <h2>group = {{list}}</h2>
                                    {% endif %}
                                {% endfor %}
                        {% endif %}

                    {% endfor %}
                {% endif %}
            </div>
            <br>

            <div style="display:inline-flex">
                {% if get %}
                    <h2>get = </h2>
                    {% for name, name2 in get.items %}
                        <h2>{{name}} : {{name2}}/</h2>
                    {% endfor %}
                {% endif %}
            </div>
            <br>

            <font size="7"><a href="{% url 'sel:all_logout' %}">logout</a></font>

            <script>
                function doReload()
                {
                    window.location.reload();
                }

                window.addEventListener('load', function ()
                {
                    setTimeout(doReload, 2500);
                });
            </script>

        </div>
    </body>
</html>

sel/templates/sel/loc.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <title>login</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">
    </head>
    <body class="container">
        <h1 class="display-4 text-primary">login</h1>
        <!--<h2 class="display-4 text-primary">{{username}}</h1>-->

        <form action="{% url 'sel:loc' %}" method="post">
            {% csrf_token %}
            <h2>username</h2>
            <input type="text" name="username_data" size="40" style="height:50px">
            <br>
            <h2>password</h2>
            <input type="text" name='password_data' size="40" style="height:50px">
            <br>
            <br>
            <input type="submit" name="click" value="click" class="btn btn-lg btn-primary">
        </form>
    </body>
</html>

sel/templates/sel/login.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <title>login</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">
    </head>
    <body class="container">
        <h1 class="display-4 text-primary">login</h1>
        <!--<h2 class="display-4 text-primary">{{username}}</h1>-->
        <form action="{% url 'sel:login' %}" method="post">
            {% csrf_token %}
            <h2>username</h2>
            <input type="text" name="username_data" autocomplete="off" size="40" style="height:50px">
            <br>
            <h2>password</h2>
            <input type="text" name='password_data' autocomplete="off" size="40" style="height:50px">
            <br>
            <br>
            <input type="submit" name="click" value="click" class="btn btn-lg btn-primary">
        </form>
    </body>
</html>

sel/templates/sel/look.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{title}}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">

    </head>

    <body>
        <div style="text-align:center">
            {% if pass %}
                {% if pass == 'OK' %}
                    {% if acount %}
                        {% for name, list in acount.items %}
                            <h3>acount = {{ name }}</h3>
                            {% for line in list %}
                                <div style="display:inline-flex">
                                    {% for column in line %}
                                        <input type="submit" name="hit" value="{{ column }}" class="btn btn-primary" style="margin:9px;height:100px;width:80px">
                                    {% endfor %}
                                </div>

                            <br>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}


                    {% if che %}
                        {% for name, list in che.items %}
                            <h3>che = {{ name }}</h3>
                            {% for line in list %}
                                <div style="display:inline-flex">
                                    {% for column in line %}
                                        <input type="submit" name="hit" value="{{ column }}" class="btn btn-primary" style="margin:9px;height:100px;width:80px">
                                    {% endfor %}
                                </div>

                            <br>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                {% endif %}

            {% endif %}

            <script>
                function doReload()
                {
                    window.location.reload();
                }

                window.addEventListener('load', function ()
                {
                    setTimeout(doReload, 2500);
                });
            </script>

            {% if message %}
            <br>
                message = {{ message }}
            {% endif %}


            {% if before_y %}
            <br>
                before_y = {{ before_y }}
            {% endif %}

            {% if before_x %}
            <br>
                before_x = {{ before_x }}
            {% endif %}

            {% if before %}
            <br>
                before = {{ before }}
            {% endif %}

            {% if word %}
            <br>
                word = {{ word }}
            {% endif %}

            {% if get %}
            <br>
                get = {{ get }}
            {% endif %}

            {% if message %}
                <br>
                message = {{ message }}
            {% endif %}

            {% if wait %}
                <br>
                wait = {{ wait }}
            {% endif %}

            {% if group %}
                <br>
                <h3>group = {{ group }}</h3>
            {% endif %}

            {% if next_player %}
                <br>
                <h3>next_player = {{ next_player }}</h3>
            {% endif %}

            {% if member_num %}
                <br>
                <h3>member_num = {{ member_num }}</h3>
            {% endif %}

            <div style="display:inline-flex">
                {% if all_get %}
                    <h2>all_get = </h2>
                    {% for name, name2 in all_get.items %}
                        <h2>{{ name }} : {{ name2 }}/</h2>
                    {% endfor %}

                {% endif %}
            </div>
            <br>

        </div>
    </body>

</html>

sel/templates/sel/signup.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <title>signup</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">
    </head>
    <body class="container">
        <h1 class="display-4 text-primary">signup</h1>
        <h2 class="display-4 text-primary">{{username}}</h1>
        <form action="{% url 'sel:signup' %}" method="post">
            {% csrf_token %}
            <h2>username</h2>
            <input type="text" name="username_data" autocomplete="off" size="40" style="height:50px">
            <h2>password</h2>
            <input type="text" name='password_data' autocomplete="off" size="40" style="height:50px">
            <br>
            <br>
            <input type="submit" name="click" value="click" class="btn btn-lg btn-primary">
        </form>
    </body>
</html>